### ISSUE TITLE
Benchmark 2.0?

### ISSUE THREAD

**Issue by mtraynham** [VicNumber21/gulp-benchmark#2]
There are quite a few bug fixes in 2.0, it'd be nice if that was supported.

**Comment by VicNumber21** [comment]
Sorry for delay with answer, I was busy on other projects.

I can see that did not wait for me and significant work is done in your fork and it has almost nothing similar with initial version =)
Do you want me still to upgrade initial version to 2.0?

**Comment by mtraynham** [comment]
No worries :) , I wasn't sure if you were still available.  

I had originally tried upgrading to 2.0 outright, and I think it had caused some of the tests to fail (I believe something with the default loader had to change).  

Also, would you prefer I create a PR for the fork instead?  It should be compatible with the current code base, but everything has just been upgraded, moved to ES6, JSDoc'd and I simplified the test suites a bit.

**Comment by VicNumber21** [comment]
In fact, you was right in assumption about my availability.
I'm not interesting in the project anymore so it is hard for me to beat my laziness to do anything here.
If you are interesting, I can pass the project to you and you will maintain it.

What I probably don't like in your changes is license change (unless you had a good reason to do it), the rest is absolutely up to you.

Please let me know if you are interesting in maintaining the project and let me know your info to make you collaborator on npmjs.com (but don't expect quick answer as usual; sorry about that)

**Comment by mtraynham** [comment]
Oh oop, I have a sample project that I typically use for setting everything up, looks like the license got copied over.  I'll revert it back to MIT.  If you feel that you are unable to maintain, then sure I'll hold on to it for you until you get back :)  Not entirely sure what information you need to add a collaborator, but my npmjs username is just `mtraynham`.

**Comment by VicNumber21** [comment]
Thanks, man!
I really appreciate that!

I've made you collaborator here and in npmjs.com.
So you should be able to merge PRs and to publish the package to npm.
Please let me know if you will have any troubles with that and I'll try to fix it.
Also polease let me know if you will need help (e.g. to review something or other things), I'll try to do what I can.

**Comment by VicNumber21** [comment]
Forgot to say, that I'm ok if you would like to use your fork as main repo.
I made you collaborator here just in case.

Thanks for reverting the license.
However, I think you need to add yourself into copyright there.
I created initial version but you re-wrote it on another level so you are author as well (and from this point probably "more author" than me =))

**Comment by mtraynham** [comment]
Close in favor of #3
